# This is a basic workflow to help you get started with Actions

name: check_schemas

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      name: "setup go"
      with:
        go-version: '1.13.4'
    - name: check schema
      run: |
        go get github.com/raid-codex/tools/cmd/raid-codex-cli
        go install github.com/raid-codex/tools/cmd/raid-codex-cli
        export PATH="/home/runner/go/bin:$PATH"
        export DIRECTORY=`pwd`
        bash scripts/check_schema.sh
