name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy API
      env:
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_HOST: ${{ secrets.FTP_HOST }}
      run: |
        BASE_DIR=`pwd` python3 scripts/deploy_api.py
